### ISSUE TITLE
PostCSS plugin ?

### ISSUE THREAD

**Issue by neolectron** [typicode/mistcss#8]
Hello, I was wondering if it was possible, or if there was a technical reason/limitation for why it isn't a postCSS plugin that could be used inside my chain of postCSS processing ?

I believe it wouldn't break the compatibility (quite the opposite), and would allow to pass an input css file that has been transformed by something else (like my auto-prefixer or whatever).

I know panda-CSS has this, and they also codegen React components.

Have a great day!

**Comment by typicode** [comment]
Hi,

For the moment, it's an early release, so I'm keeping things simple.

>  input css file that has been transformed by something else (like my auto-prefixer or whatever).

MistCSS is a bit different from other solutions. It works with auto-prefixer, tailwind, ... or whatever plugin is used because the CSS is not modified. It doesn't need to be aware if you're using LightningCSS or PostCSS. 

Since the React components are real files (that you didn't write) and just import the `.mist.css` file, it goes through the CSS pipeline that's setup for the project.

In the future, I do plan to have more integrations though :)

Have a great day as well :+1:

**Comment by typicode** [comment]
It's now a PostCSS plugin ;)
